<?xml version="1.0" encoding="utf-8"?><Database Name="linqlesson01" Class="ContactDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=linqlesson01;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True" SettingsObjectName="LinqToSqlLesson02.Properties.Settings" SettingsPropertyName="linqlesson01ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Contact" Member="Contact">
    <Type Name="Contact">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Memo" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
    </Type>
  </Table>
</Database>